[workspace]
resolver = "3"
members = [
	"macros_logger",
	"use_macros_logger",
	"macros_function_decorator",
	"using_syn",
	"tools/*",
]

[workspace.dependencies]
env_logger = "0.11.8"
log = "0.4.27"
